### PR TITLE
Allow pasting emoji unicodes into text area

### LINKED ISSUE #192: Pasting text with emoji unicodes into EmojiTextArea should replace them with ImageViews

### PR DESCRIPTION
**Pull request by jperedadnr**
Fixes #192

### CODE REVIEW

**Comment by abhinayagarwal** [comment]
Tried pasting an emoji and instead of the image, it shows the text representation of the emoji.

image

**Comment by jperedadnr** [comment]
can you paste the same content into your IDE, inside a String with "", See
the demo case: you should see the unicode.

**Comment by jperedadnr** [comment]
I see, you are right, the demo works when the text is added via the button because that goes to the `EmojiTextArea::textProperty`, but copy/paste doesn't work, because that goes to inner `EmojiStyledTextArea::textProperty`.

**Comment by jperedadnr** [comment]
@abhinayagarwal It should be fixed now.

**Review by abhinayagarwal — APPROVED** [review]

**Pull request merged**
