### PR TITLE
Replace VirtualFlow and duplicated classes with ChatVirtualFlow

### LINKED ISSUE #184: Remove duplicated classes from OpenJFX
Since JavaFX 12, most of VirtualFlow needed methods are accessible

### PR DESCRIPTION
**Pull request by jperedadnr**
Fixes #184

### CODE REVIEW

**Comment by abhinayagarwal** [comment]
This works and is definitely better than the previous implementation. However, its still not perfect. It feels we are scrolling too much  on each mouse scroll action.

**Comment by abhinayagarwal** [comment]
Also, the scroll action is too fast which makes the view jump instead of smooth scroll.

**Comment by johanvos** [comment]
Maybe we should merge and use it already then, so that we can collect feedback before making additional changes?

**Comment by abhinayagarwal** [comment]
I am ok with it

**Review by abhinayagarwal — APPROVED** [review]

**Pull request merged**
